server:
  port: 8081
spring:
  datasource:
    password: 31e09ef9
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/ heroku_723ff157fe14dfe
    username: bcc6f80a16f609
    hikari:
      maxLifetime: 20000
    mvc:
    pathmatch:
    matching-strategy : ANT_PATH_MATCHER
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true